Repository lassejonassen/handballmatchreg, pull requests merged in 2021-01, with the labels that each got.

#54 spCreateMatch og begyndelse på CRUD suspension
  .classpath
  sqlscripts/Stored Procedures/spDeleteMatch.sql
  src/data/DataLayer.java
  src/logic/MatchImpl.java
  src/logic/iMatch.java
  src/presentation/CreateSuspension.java
Labels: wontfix

#56 Added logic and data methods to update match
  sqlscripts/Stored Procedures/spUpdateMatch.sql
  src/data/DataLayer.java
  src/logic/MatchImpl.java
  src/logic/iMatch.java
  src/presentation/LigaMenu.java
  src/presentation/Main.java
  src/presentation/MatchMenu.java
  src/presentation/Menu.java
  src/presentation/UpdateTeam.java
Labels: enhancement

#62 Oprydning i kode
  src/data/DataLayer.java
  src/data/Suspension.java
  src/logic/MatchImpl.java
  src/logic/iMatch.java
  src/presentation/DeleteMatch.java
  src/presentation/MatchMenu.java
Labels: Cleaning

#68 in the making - ignore this
  src/data/DataLayer.java
  src/logic/TeamImpl.java
  src/presentation/LigaMenu.java
  src/presentation/MatchDetails.java
Labels: enhancement

#69 TeamScoreUpdate
  .classpath
  sqlscripts/Stored Procedures/spGetMatchesByLeagueID.sql
  sqlscripts/Stored Procedures/spGetOneTeam.sql
  sqlscripts/Stored Procedures/spUpdateTeamScore.sql
  src/data/DataLayer.java
  src/data/Match.java
  src/data/Team.java
  src/logic/MatchImpl.java
  src/presentation/MatchDetails.java
  src/presentation/MatchMenu.java
Labels: enhancement

#70 Added SP
  sqlscripts/Stored Procedures/spGetGoalsAndSuspensions.sql
  src/data/DataLayer.java
  src/logic/TeamImpl.java
  src/logic/iMatch.java
  src/presentation/CreateMatch.java
  src/presentation/DeleteMatch.java
  src/presentation/LigaMenu.java
  src/presentation/MatchDetails.java
  src/presentation/MatchMenu.java
Labels: enhancement

#74 ReportDTO
  .classpath
  sqlscripts/Stored Procedures/spGetGoalsAndSuspensions.sql
  src/data/DataLayer.java
  src/data/Goal.java
  src/data/ReportDTO.java
  src/data/Suspension.java
  src/logic/ReportDTOImpl.java
  src/logic/iReportDTO.java
  src/presentation/Main.java
  src/presentation/MatchDetails.java
Labels: enhancement

#78 Forskelling funktioner
  sqlscripts/Stored Procedures/spCreateMatch.sql
  sqlscripts/Stored Procedures/spGetMatchesByLeagueID.sql
  sqlscripts/Stored Procedures/spUpdatePlayedMatch.sql
  sqlscripts/dbsetup.sql
  src/data/DataLayer.java
  src/data/Match.java
  src/data/Team.java
  src/logic/MatchImpl.java
  src/logic/iMatch.java
  src/presentation/Layout.java
  src/presentation/LigaMenu.java
  src/presentation/Main.java
  src/presentation/MatchDetails.java
  src/presentation/MatchMenu.java
  src/presentation/Menu.java
  src/presentation/Validation.java
Labels: enhancement

#84 luk knap
  .classpath
  src/presentation/MatchDetails.java
Labels: enhancement

#86 Export matchreport, leaguetable sorting
  .classpath
  archives/opencsv-5.3.jar
  src/data/ReportDTO.java
  src/presentation/LigaMenu.java
  src/presentation/MatchReport.java
Labels: enhancement

#95 Data import
  src/logic/GoalImpl.java
  src/logic/MatchImpl.java
  src/logic/SuspensionImpl.java
  src/logic/iGoal.java
  src/logic/iMatch.java
  src/logic/iSuspension.java
  src/presentation/ImportMatch.java
  src/presentation/MatchDetails.java
  src/presentation/MatchReport.java
Labels: enhancement

#101 Db, errors, buttons
  sqlscripts/dbsetup.sql
  src/presentation/CreateTeam.java
  src/presentation/LigaMenu.java
  src/presentation/MatchMenu.java
  src/presentation/Validation.java
Labels: Bug fix, Code clean-up, Enhancement
